### PR TITLE
Fix: Silver dragon scaled armor was not granting cold resistance.

### PR DESCRIPTION
**Pull request by elunna**
On the EvilHack wiki I noticed it says it grants cold res.

This is my first PR, do I usually target the master branch?

### CODE REVIEW

**Comment by k21971** [comment]
Hi! Yes, targeting the master branch is fine.

Also, you can close this PR... thanks though! I purposely removed silver dragon scales imparting cold resistance a ways back in commit 82ba30c - if it's still reporting this on the wiki, it's wrong.

**Comment by k21971** [comment]
Hold up, don't close it. Lemme think on it. I need to talk to past me and see what he was thinking.

**Comment by elunna** [comment]
Ok ok - I thought it made sense because silver dragons breathe cold :)

**Comment by k21971** [comment]
I think past me pulled cold res away from silver dragons because I did the same for gold dragons/fire res. But gold dragons have a secondary intrinsic (sick res) and silver dragons haven't had one at all since Feb 2022. Since they have a cold breath attack, it would make sense that it be returned.

**Pull request merged**
